services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "23798:5432"
    shm_size: 1gb
    volumes:
      - db_data:/var/lib/postgresql/data
  uniswapv2:
    image: uniswapv2
    environment:
      DB_NAME: postgres
      GQL_PORT: 4350
      GATEWAY_URL: "https://v2.archive.subsquid.io/network/ethereum-mainnet"
      CHAIN_ID: 1
      RPC_URL: "https://eth-mainnet.g.alchemy.com/v2/***REMOVED***"
      CONTRACT_ADDRESS: '0xa43fe16908251ee70ef74718545e4fe6c5ccec9f'
      # DB_PORT: 23798
      DB_URL: 'postgres://postgres:postgres@db:5432/postgres'
      FROM_BLOCK: 17046833
      TO_BLOCK: 17070370
      TOKEN0_COINGECKO_ID: 'pepe'
      TOKEN1_COINGECKO_ID: 'weth'
      PREFERRED_TOKEN_COINGECKO_ID: 'token1'
      COINGECKO_API_KEY: '***REMOVED***'
      ABSINTHE_API_URL: 'http://host.docker.internal:3000'
      ABSINTHE_API_KEY: 'api_key_2'
      BALANCE_FLUSH_INTERVAL_HOURS: 6

volumes:
  db_data:


networks:
  squid:
    driver: bridge
