services:
  caddy:
    image: caddy:latest
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
  abs-app:
    image: ghcr.io/absinthelabs/absinthe-abs-app:abs-app
    ports:
      - 3000:3000
    depends_on:
      - caddy
    env_file:
      - .env
    networks:
      - absinthe-net

    command: npm start
  abs-app-main:
    image: ghcr.io/absinthelabs/absinthe-abs-app:abs-app
    ports:
      - 3005:3005
    depends_on:
      - caddy
    env_file:
      - .env.main
    networks:
      - absinthe-net

    command: npm start
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - absinthe-net
    volumes:
      - redis_data:/data

networks:
  absinthe-net:
    driver: bridge

volumes:
  caddy_data:
