services:
  caddy:
    image: caddy:latest
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
  abs-app:
    image: ghcr.io/absinthelabs/absinthe-abs-app:abs-app
    ports:
      - 3000:3000
    depends_on:
      - caddy
    env_file:
      - .env
    volumes:
      - ./abs-app:/app
    command: npm start

volumes:
  caddy_data:


  