name: Build & Push Docker Images to GHCR

on:
  pull_request:
    types: [closed]
    branches: [develop]

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine SemVer
        id: semver
        run: |
          VERSION="$(git tag --points-at HEAD | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' || true)"
          if [ -z "$VERSION" ]; then
            echo "No exact semver tag on this commit, skipping versioned push."
          else
            echo "SemVer detected: $VERSION"
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push all Docker images
        run: |
          # Find all Dockerfiles
          dockerfiles=$(find ops/dockerfiles -name "Dockerfile*" -type f)

          if [ -z "$dockerfiles" ]; then
            echo "No Dockerfiles found in ops/dockerfiles"
            exit 0
          fi

          # Build and push each image sequentially
          for dockerfile_path in $dockerfiles; do
            dockerfile=$(basename "$dockerfile_path")
            echo "Building $dockerfile..."
            
            # Extract image name
            if [[ "$dockerfile" == "Dockerfile" ]]; then
              image_name="main"
            else
              image_name=$(echo "$dockerfile" | sed 's/Dockerfile[.-]*//' | tr '[:upper:]' '[:lower:]')
            fi
            
            tags="ghcr.io/absinthelabs/absinthe-${image_name}:latest"
            
            # if VERSION is set, add the semver tag
            if [ -n "${VERSION:-}" ]; then
              tags="$tags ghcr.io/absinthelabs/absinthe-${image_name}:$VERSION"
            fi

            echo "Building + pushing ${image_name} → tags: $tags"
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --file "$dockerfile_path" \
              --push \
              $(printf -- "--tag %s " $tags) \
              .
          done

  deploy:
    runs-on: ubuntu-22.04
    needs: build-and-push
    steps:
      - name: Trigger deployment on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_STG_DEV_HOST }}
          username: ${{ secrets.EC2_STG_DEV_USER }}
          key: ${{ secrets.EC2_STG_DEV_SSH_KEY }}
          script: |
            bash /home/admin/ops/absinthe-api/deploy-absinthe.sh
