name: Build & Push Docker Images to GHCR

on:
  push:
    branches: [kushagra/improvements]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.dockerfiles.outputs.matrix }}
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    
    - name: Get Dockerfile list
      id: dockerfiles
      run: |
        dockerfiles=$(find ops/dockerFile -name "Dockerfile*" -type f | sed 's|ops/dockerFile/||' | jq -R -s -c 'split("\n")[:-1]')
        echo "matrix=$dockerfiles" >> $GITHUB_OUTPUT

  build-and-push:
    needs: prepare
    runs-on: ubuntu-latest
    if: ${{ fromJson(needs.prepare.outputs.matrix)[0] != '' }}

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        dockerfile: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract image name
      id: image-name
      run: |
        dockerfile_path="${{ matrix.dockerfile }}"
        if [[ "$dockerfile_path" == "Dockerfile" ]]; then
          image_name="main"
        else
          image_name=$(echo "$dockerfile_path" | sed 's/Dockerfile[.-]*//' | tr '[:upper:]' '[:lower:]')
        fi
        echo "name=$image_name" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ops/dockerFile/${{ matrix.dockerfile }}
        push: true
        tags: ghcr.io/absinthelabs/absinthe-uniswapv2:${{ steps.image-name.outputs.name }}
